version: "3.7"

services:

    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-app/Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - mynetwork

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8988:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - mynetwork

    postgresql11:
        image: postgres:11.7
        restart: always
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            PGDATA: ${PG_DATA}
        volumes:
            - postgres:/data/postgres

        ports:
            - "5440:5432"
        networks:
            - mynetwork

    redis:
        image: redis:latest
        networks:
            - mynetwork

    vue-app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-vue/Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/src/app
        depends_on:
            - redis
        networks:
            - mynetwork

volumes:
    postgres:
    pg-data:


networks:
    mynetwork:
        driver: bridge
